import type { Lead } from '@/types/lead.types'

export const mockLeads: Lead[] = [
  {
    id: '1',
    name: 'Andrei Popescu',
    handle: '@andrei.pop',
    manychat_user_id: 'mc_001',
    status: 'exploring',
    current_phase: 'P4',
    message_count: 8,
    assigned_to: 'user_maria',
    assigned_to_name: 'Maria',
    tags: ['hot', 'ecommerce'],
    needs_human: false,
    bot_paused: false,
    is_blocked: false,
    is_new: false,
    is_returning: false,
    has_errors: false,
    last_message_at: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
  },
  {
    id: '2',
    name: 'Maria Ionescu',
    handle: '@maria.ion',
    manychat_user_id: 'mc_002',
    status: 'exploring',
    current_phase: 'P3',
    message_count: 12,
    tags: ['urgent'],
    needs_human: true,
    bot_paused: false,
    is_blocked: false,
    is_new: false,
    is_returning: false,
    has_errors: false,
    last_message_at: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
  },
  {
    id: '3',
    name: 'Elena Matei',
    handle: '@elena.mat',
    manychat_user_id: 'mc_003',
    status: 'booked',
    current_phase: 'P7',
    message_count: 15,
    assigned_to: 'user_sergiu',
    assigned_to_name: 'Sergiu',
    tags: ['success', 'fast-close'],
    needs_human: false,
    bot_paused: true,
    is_blocked: false,
    is_new: false,
    is_returning: false,
    has_errors: false,
    last_message_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: '4',
    name: 'Dan Popa',
    handle: '@dan.popa',
    manychat_user_id: 'mc_004',
    status: 'likely_qualified',
    current_phase: 'P4',
    message_count: 9,
    tags: ['interested'],
    needs_human: false,
    bot_paused: false,
    is_blocked: false,
    is_new: false,
    is_returning: false,
    has_errors: false,
    last_message_at: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
  },
  {
    id: '5',
    name: 'Ion Radu',
    handle: '@ion.radu',
    manychat_user_id: 'mc_005',
    status: 'new',
    current_phase: 'P1',
    message_count: 2,
    tags: [],
    needs_human: false,
    bot_paused: false,
    is_blocked: false,
    is_new: false,
    is_returning: false,
    has_errors: false,
    last_message_at: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
  },
  {
    id: '6',
    name: 'Diana Luca',
    handle: '@diana.luca',
    manychat_user_id: 'mc_006',
    status: 'qualified',
    current_phase: 'P6',
    message_count: 14,
    assigned_to: 'user_maria',
    assigned_to_name: 'Maria',
    tags: ['qualified', 'ready'],
    needs_human: false,
    bot_paused: false,
    is_blocked: false,
    is_new: false,
    is_returning: false,
    has_errors: false,
    last_message_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
  },
  {
    id: '7',
    name: 'Mihai Stan',
    handle: '@mihai.stan',
    manychat_user_id: 'mc_007',
    status: 'nurture',
    current_phase: 'P5',
    message_count: 11,
    tags: ['follow-up'],
    needs_human: false,
    bot_paused: false,
    is_blocked: false,
    is_new: false,
    is_returning: false,
    has_errors: false,
    last_message_at: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
  },
  {
    id: '8',
    name: 'Ana Gheorghe',
    handle: '@ana.geo',
    manychat_user_id: 'mc_008',
    status: 'not_fit',
    current_phase: 'P3',
    message_count: 6,
    tags: ['not-interested'],
    needs_human: false,
    bot_paused: true,
    is_blocked: false,
    is_new: false,
    is_returning: false,
    has_errors: false,
    last_message_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '9',
    name: 'Cristian Dumitrescu',
    handle: '@cristi.d',
    manychat_user_id: 'mc_009',
    status: 'exploring',
    current_phase: 'P2',
    message_count: 5,
    tags: ['new-lead'],
    needs_human: false,
    bot_paused: false,
    is_blocked: false,
    is_new: false,
    is_returning: false,
    has_errors: true,
    last_message_at: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
  },
  {
    id: '10',
    name: 'Roxana Munteanu',
    handle: '@roxana.m',
    manychat_user_id: 'mc_010',
    status: 'likely_qualified',
    current_phase: 'P5',
    message_count: 13,
    assigned_to: 'user_sergiu',
    assigned_to_name: 'Sergiu',
    tags: ['high-intent', 'budget-ok'],
    needs_human: false,
    bot_paused: false,
    is_blocked: false,
    is_new: false,
    is_returning: false,
    has_errors: false,
    last_message_at: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 7 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
  },
]
